### ISSUE TITLE
Fatal error: SGGeodesy::distanceM, unable to compute distance

### ISSUE THREAD

**Issue by pedromorgan** [pedromorgan/flightgear-issues-test#79]
_From [angisang...@yahoo.com](https://code.google.com/u/101683260209624192770/) on February 15, 2010 22:24:36_

What steps will reproduce the problem? 1. Start FG at NZAA, Rwy standard (I used the 777-200ER)
2. Take off
3. Climb to 2800 ft, HDG=230, IAS=260-300
5. Fly straight ahead through Wattle Bay and wait a short time What is the expected output? What do you see instead? After passing the land at Wattle Bay entry, FG crashes with error ouput on
console: Fatal error: SGGeodesy::distanceM, unable to compute distance What version of the product are you using? On what operating system? FG 2.0, Win32 with x64 Extension Please provide any additional information below. Crash happens at about 174.524002 / -37.044217
Tested with activated AP and in manual flight
Carsh does not happen with Cessna 172R

_Original issue: http://code.google.com/p/flightgear-bugs/issues/detail?id=80_

**Comment by pedromorgan** [comment]
_From [angisang...@yahoo.com](https://code.google.com/u/101683260209624192770/) on February 15, 2010 14:25:30_

Sent too early. Crash happens with Cessna 172R, too.

**Comment by pedromorgan** [comment]
_From [zakalawe@mac.com](https://code.google.com/u/zakalawe@mac.com/) on February 15, 2010 14:35:29_

Quite a high chance this is mine.

**Cc:** zakal...@mac.com

**Comment by pedromorgan** [comment]
_From [angisang...@yahoo.com](https://code.google.com/u/101683260209624192770/) on February 15, 2010 15:17:51_

The try of a C++ illiterate to produce some trace: http://pastebin.ca/1797758

**Comment by pedromorgan** [comment]
_From [zakalawe@mac.com](https://code.google.com/u/zakalawe@mac.com/) on February 16, 2010 01:18:38_

Reproduced here, will hopefully grab a back-trace next time.

**Comment by pedromorgan** [comment]
_From [angisang...@yahoo.com](https://code.google.com/u/101683260209624192770/) on February 16, 2010 12:05:15_

As stated in irc today the used debug binaries and core dump at moment of error are
online for analysis. Link will follow.

**Comment by pedromorgan** [comment]
_From [zakalawe@mac.com](https://code.google.com/u/zakalawe@mac.com/) on February 16, 2010 15:00:06_

Backtrace: it's the traffic-manager code.

\#0  SGGeodesy::distanceM (p1=@0xbfffef30, p2=@0xbfffef18) at 
/Users/jmt/Code/Macflightgear/SimGear/SimGear/simgear/math/SGGeodesy.cxx:468
\#1  0x003eb5aa in SGGeodesy::distanceNm (from=@0xbfffef30, to=@0xbfffef18) at 
/Users/jmt/Code/Macflightgear/SimGear/SimGear/simgear/math/SGGeodesy.cxx:477
\#2  0x00232030 in FGAISchedule::update (this=0x247b54f0, now=1266360990) at 
/Users/jmt/Code/Macflightgear/flightgear/FlightGear/src/Traffic/Schedule.cxx:361
\#3  0x00236e9a in FGTrafficManager::update (this=0x231307c0) at 
/Users/jmt/Code/Macflightgear/flightgear/FlightGear/src/Traffic/TrafficMgr.cxx:149
\#4  0x0030d697 in SGSubsystemGroup::Member::update (this=0x23130890, 
delta_time_sec=0.016666666666666666) at 
/Users/jmt/Code/Macflightgear/SimGear/SimGear/simgear/structure/subsystem_mgr.cxx:310
\#5  0x0030f92b in SGSubsystemGroup::update (this=0x220b01c, delta_time_sec=0.016666666666666666) 
at /Users/jmt/Code/Macflightgear/SimGear/SimGear/simgear/structure/subsystem_mgr.cxx:163

**Comment by pedromorgan** [comment]
_From [zakalawe@mac.com](https://code.google.com/u/zakalawe@mac.com/) on February 16, 2010 16:21:22_

Testing a fix for this. but it's somewhat intrusive (in the trafficmanager code), so please be patient.

**Status:** Dev  
**Labels:** traffic

**Comment by pedromorgan** [comment]
_From [zakalawe@mac.com](https://code.google.com/u/zakalawe@mac.com/) on March 14, 2010 04:20:22_

Fixed! Changed the traffic manager to use cartesian distance computations, which are stable over the global 
distances involved.

**Status:** Fixed

**Comment by pedromorgan** [comment]
_From [zakalawe@mac.com](https://code.google.com/u/zakalawe@mac.com/) on April 07, 2010 15:40:28_

Issue 116 has been merged into this issue.

**Comment by pedromorgan** [comment]
_From [bre...@gmail.com](https://code.google.com/u/112567806978334989774/) on June 05, 2011 02:52:29_

**Status:** Temp

**Comment by pedromorgan** [comment]
_From [bre...@gmail.com](https://code.google.com/u/112567806978334989774/) on June 05, 2011 02:52:48_

**Status:** Fixed

**Comment by pedromorgan** [comment]
_From [gijsrooy](https://code.google.com/u/gijsrooy/) on July 15, 2011 05:07:21_

**Labels:** Milestone-2.0.0

**Comment by pedromorgan** [comment]
_From [gijsrooy](https://code.google.com/u/gijsrooy/) on July 15, 2011 05:08:38_

Eh, fixed *after* the 2.0.0 release, so Milestone-2.4.0

**Labels:** -Milestone-2.0.0 Milestone-2.4.0
